### ISSUE TITLE
Allow alternate domain for the variable entity

### ISSUE THREAD

**Issue by iprak** [Wibias/hass-variables#17]
I have locally modified the code to allow an override domain. This entity appears as `sensor.daily_download` instead of `variable.daily_download`.

```
variable:
  daily_download:
    value: 0
    restore: true
    domain: sensor
```

This entity can still be updated via the `set_variable` service (with some modifications),. What do you think about this? I can submit a pull request.
