### ISSUE TITLE
Automation doesn't work anymore and shows error

### ISSUE THREAD

**Issue by johanvh83** [Wibias/hass-variables#20]
I use your repro to list the 10 last actions of many motion sensors.
It worked for a long time but recently it doesn't work anymore.
I had a look and found an error in the trace of the automation:

Stopped because an error was encountered at August 13, 2022 at 8:05:55 PM (runtime: 0.16 seconds)
wait() got an unexpected keyword argument 'loop'

Even after upgrade to your latest version V2.3.0 (but manifest.json remains on V2.2.2) the error remains.

**Comment by Wibias** [comment]
Can you show your config? For me it works just fine.

**Comment by johanvh83** [comment]
Hi Wibias, thanks for you answer.
This is my full configuration:

configuration.yaml:

variable:
  last_motion:
    value: 'Not set'
    restore: true
    attributes:
      icon: mdi:map-marker
      name: 'Last Motion'

automation.yaml

- id: c6502b9ee9fb4c8b9a496c2b78240f3e
  alias: Motion Update
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.motionsensor_garage_occupancy
    - binary_sensor.motionsensor_keuken_occupancy
    - binary_sensor.motionsensor_hall_occupancy
    - binary_sensor.motionsensor_living_occupancy
    - binary_sensor.motionsensor_wc_occupancy
    - binary_sensor.motionsensor_boven_occupancy
    to: 'on'
  action:
  - service: variable.set_variable
    data:
      variable: last_motion
      attributes:
        history_1: '{{ states(''variable.last_motion'') }}'
        history_2: '{{ state_attr(''variable.last_motion'',''history_1'') }}'
        history_3: '{{ state_attr(''variable.last_motion'',''history_2'') }}'
        history_4: '{{ state_attr(''variable.last_motion'',''history_3'') }}'
        history_5: '{{ state_attr(''variable.last_motion'',''history_4'') }}'
        history_6: '{{ state_attr(''variable.last_motion'',''history_5'') }}'
        history_7: '{{ state_attr(''variable.last_motion'',''history_6'') }}'
        history_8: '{{ state_attr(''variable.last_motion'',''history_7'') }}'
        history_9: '{{ state_attr(''variable.last_motion'',''history_8'') }}'
        history_10: '{{ state_attr(''variable.last_motion'',''history_9'') }}'
  - service: variable.set_variable
    data:
      variable: last_motion
      value: '{{ trigger.to_state.attributes.friendly_name }} : {{ as_timestamp(trigger.to_state.last_changed)|
        timestamp_custom(''%x, %X'') }}'
  mode: single

Lovelace card configuartion:

type: custom:entity-attributes-card
title: Last movements in house
heading_name: Name
heading_state: Status
entity: variable.last_motion
filter:
  include:
    - variable.last_motion.history_1
    - variable.last_motion.history_2
    - variable.last_motion.history_3
    - variable.last_motion.history_4
    - variable.last_motion.history_5
    - variable.last_motion.history_6
    - variable.last_motion.history_7
    - variable.last_motion.history_8
    - variable.last_motion.history_9

The Lovelace cards shows the last movements from 7 november 2021...

The automation is triggered:
<img width="1396" alt="Schermafbeelding 2022-09-11 om 13 13 43" src="https://user-images.githubusercontent.com/76775686/189524399-4bd5bf58-0de5-4604-852a-1a3ddf0d6053.png">

but the action fails:

<img width="1420" alt="Schermafbeelding 2022-09-11 om 13 15 46" src="https://user-images.githubusercontent.com/76775686/189524477-e7414455-bb80-4a10-9417-aee720c2ea13.png">

**Comment by Wibias** [comment]
Thats what my automation looks like. Feel free to try it. Also your code is hard to read. Please use githubs code next time.

```
  - alias: Motion - Last Motion
    id: '54723567356536756745673567'
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          binary_sensor.badezimmer_motion_sensor, binary_sensor.flur_motion_sensor,
          binary_sensor.kueche_motion_sensor, binary_sensor.schlafzimmer_motion_sensor,
          binary_sensor.wohnzimmer_motion_sensor
        to: "on"
    action:
      - service: variable.set_variable
        data:
          variable: last_motion
          attributes:
            history_1: "{{states('variable.last_motion')}}"
            history_2: "{{state_attr('variable.last_motion','history_1')}}"
            history_3: "{{state_attr('variable.last_motion','history_2')}}"
            history_4: "{{state_attr('variable.last_motion','history_3')}}"
            history_5: "{{state_attr('variable.last_motion','history_4')}}"
            history_6: "{{state_attr('variable.last_motion','history_5')}}"
            history_7: "{{state_attr('variable.last_motion','history_6')}}"
          value: >
            {{trigger.to_state.name|replace('Motion Sensor','')}}
```
