### ISSUE TITLE
After the update, all the variables went to initial state

### ISSUE THREAD

**Issue by pickonedev** [Wibias/hass-variables#27]
Hi!

I made the last update, but after this, I lost all my variables values, which are configured as "restore: true" ...

Edit: Oh, it is even worst... now it will reset my values after each restart. All the variables are acting like I would have "restore: false" set...

This is an example of what I use as variable:

```
bedroom_pir:
  value: initial
  restore: true
  attributes:
    icon: mdi:walk
```

Every restart, will add "initial" value to my variables...

Edit2: I have downgraded to 2.3.3 and everything works good... Seems that there is a problem with the new 2.3.5 version
