### ISSUE TITLE
unit_of_measurement: not working

### ISSUE THREAD

**Issue by letsid** [Wibias/hass-variables#28]
Hi,

it seems unit of measurement is not working 

```
  grid_consumption_1_daily_yesterday:
    value: "Not set"
    restore: true
    attributes:
      friendly_name: "Netzbezug gestern"
      state_class: measurement
      unit_of_measurement: kWh

```
![image](https://user-images.githubusercontent.com/22770820/215720023-7f2cabb7-1a6a-4d69-b379-53482dbf80c8.png)

I though creating a template sensor which just stores the value in an other sensor to show it correctly but iis possible to use the unit_of measurement directly I would like to do it.
br,
letsid
