### ISSUE TITLE
Changes to value of variables not picked up by alert integration

### ISSUE THREAD

**Issue by cerebrate** [Wibias/hass-variables#67]
There seems to be an issue with changes to the value of variables not being picked up by the alert integration (and possibly other integrations that use the same mechanism).

In context, I'm using a binary_sensor variable to transform a momentary event into a state that persists until manually cancelled. Having defined the variable, I set it when the event occurs and reset it when the user cancels with the `variable.update_binary_sensor` service. This works correctly: inspecting the value of the variable with the developer tools shows its value changing appropriately.

However, I then define an alert based on the value of the variable:

```
  alert:
    # An appliance beeped recently.
    appliance_beeped_recently:
      name: Appliance Beeped Recently
      entity_id: binary_sensor.appliance_beeps_recently
      state: 'on'
      repeat: 10
      skip_first: false
      message: "An appliance is beeping in the kitchen."
      notifiers:
        - loud
```

And this doesn't work. When the variable `binary_sensor.appliance_beeps_recently` changes state to `on`, the alert stays in `idle`, untriggered.

As a temporary workaround, if I define a simple binary sensor template which just passes through the state of the variable:

```
  template:
    - binary_sensor:
        - name: appliance_beeps_workaround
          state: "{{ states('binary_sensor.appliance_beeps_recently') }}"
```

the state of the template changes in sync with the state of the variable, as it should, and if I then use the binary sensor _created by the template_ in the alert, the alert works correctly then, even though it doesn't work when configured to use the variable directly. So it looks like there's something funky in how this integration and alert play together...
