### ISSUE TITLE
Timer Example throws out an 'UndefinedError' [SOLVED]

### ISSUE THREAD

**Issue by 3ative** [Wibias/hass-variables#7]
I've setup the **Variable** (_variable.testing_one_) and can change the state, so that bit is working.
- However, I can't get an Automation to work.
I'm running this, from the Timer Example:
```yaml
action:
  - service: variable.set_variable
    data:
      variable: testing_one
      value: |
        {{ [((variable.state | int) - 1), 0] | max }}
```
and getting this:
"Error: Error rendering data template: UndefinedError: 'variable' is undefined"

Any ideas?

**Comment by Wibias** [comment]
So I narrowed it down to being the 
`      value: |
        {{ [((variable.state | int) - 1), 0] | max }}`
part. Didnt have any more time yet. Tbh that part was just copy pasted from the rogro repo.

**Comment by 3ative** [comment]
> value: >
>     {{ [((states.variable.testing_one.state | int) - 1), 0] | max }}```

I tried that, it worked-ish. 👍
I edited your code to:
```yaml
  value: |
    {{ [((states.variable.testing_one.state | int) - 1), 0] | max }}
```
I removed the trailing 'tick' marks and now it works - thanks.

**Comment by 3ative** [comment]
@Wibias 
Should I make a PR to update the code examples ?
Or, now that you know about it, will you do the necessary editing.

**Comment by Wibias** [comment]
I will do it in some minutes. Thanks for the response!

**Comment by 3ative** [comment]
@Wibias 
Addition:
I just looked at the yaml again, after a reload and HA changed it to this:
```yaml
  action:
    - service: variable.set_variable
      data:
        variable: testing_one
        value: "{{ [((states.variable.testing_one.state | int) - 1), 0] | max }}"
 ```
 Notice the quotes on the 'value:' line.

**Comment by Wibias** [comment]
For me it doesnt  add the quotes but I am also using '>'

**Comment by 3ative** [comment]
@Wibias 

> For me it doesnt add the quotes but I am also using '>'

Well that's weird, I just checked again and for some reason it's changed it to single quotes now!!! 
```yaml
  action:
  - service: variable.set_variable
    data:
      variable: testing_one
      value: '{{ [((states.variable.testing_one.state | int) - 1), 0] | max }}'
```

Also, if I save using the '>' that gets changed to a pipe '|' !
