### ISSUE TITLE
Error calling set_variable Service - RuntimeError: Cannot modify ReadOnlyDict

### ISSUE THREAD

**Issue by Snuffy2** [Wibias/hass-variables#82]
I have tried right now but I get error... Any idea?

Variable has been defined like this, into variable.yaml file

```
variable_last_state:
  value: ""
  restore: true
```

which means that I have a sensor.variable_last_state entity

![image](https://github.com/Wibias/hass-variables/assets/34201387/e638e77f-b546-44eb-9754-9a0a465468ea)

With this is working to change the value

```
service: variable.update_sensor
data:
  value: ok
target:
  entity_id: sensor.variable_last_state
```

But I need to use the legacy version

_Originally posted by @pickonedev in https://github.com/Wibias/hass-variables/issues/80#issuecomment-1632550157_
