### ISSUE TITLE
Setting to blank sets to 'unknown'

### ISSUE THREAD

**Issue by rwarner** [Wibias/hass-variables#89]
Thanks for forking and continuing to work on this from rogro82's

Since moving over to this forked repo, I noticed that when I `variable.update_sensor` to nothing at all (i.e. `""`) It seems to set the state to `unknown`

```
- service: variable.update_sensor
      data:
        value: ""
      target:
        entity_id: sensor.value
```

Not sure if this is intentional. I tweaked some of my logic in my automations to accommodate but thought I'd report.
